import type {
  LLMClient,
  LLMCompletionRequest,
  LLMCompletionResponse,
} from './types'

export const MOCK_BASE_URL = 'mock://local'

// Pull the last message with the given role so the mock can echo parts back,
// making it obvious in DevTools that the template's params flowed through.
function lastContent(req: LLMCompletionRequest, role: 'system' | 'user'): string {
  for (let i = req.messages.length - 1; i >= 0; i--) {
    if (req.messages[i].role === role) return req.messages[i].content
  }
  return ''
}

// Route by sniffing the system message — each template begins with a verb
// phrase like "You name and describe items …" that tells us which payload
// shape to return. Keeps template authorship decoupled from the mock.
function mockResponse(system: string, user: string): string {
  if (/name and describe items/i.test(system)) {
    const kind = user.match(/Kind:\s*([a-z]+)/i)?.[1] ?? 'item'
    const hint = user.match(/Hint:\s*([^.]+)\./i)?.[1]?.trim() ?? 'a curious thing'
    return JSON.stringify({
      name: `Mock ${kind}: ${hint.slice(0, 40)}`,
      description: `A placeholder ${kind} generated by the mock for pipeline testing.`,
    })
  }
  if (/name and describe mobs/i.test(system)) {
    const hint = user.match(/Mob hint:\s*([^.(]+)/i)?.[1]?.trim() ?? 'an unnamed creature'
    return JSON.stringify({
      name: `Mock ${hint.slice(0, 30)}`,
      description: `A placeholder mob (${hint}) generated by the mock for pipeline testing.`,
    })
  }
  if (/name and describe areas/i.test(system)) {
    const kind = user.match(/Area kind:\s*([^.]+)\./i)?.[1]?.trim() ?? 'area'
    const hint = user.match(/Hint:\s*([^.]+)\./i)?.[1]?.trim() ?? 'a notable place'
    return JSON.stringify({
      name: `Mock ${kind}`,
      description: `A placeholder ${kind} (${hint}) generated by the mock for pipeline testing.`,
      theme: `mock ${kind.toLowerCase()}`,
    })
  }
  if (/name and describe individual rooms/i.test(system)) {
    const roomType = user.match(/Room type:\s*([^.]+)\./i)?.[1]?.trim() ?? 'room'
    const areaTheme = user.match(/theme:\s*([^)]+)\)/i)?.[1]?.trim() ?? 'generic'
    return JSON.stringify({
      name: `Mock ${roomType}`,
      description: `A placeholder ${roomType} keyed to the area's ${areaTheme} theme, for pipeline testing.`,
    })
  }
  if (/write short lore snippets/i.test(system)) {
    const topic = user.match(/Topic:\s*([^.]+)\./i)?.[1]?.trim() ?? 'something'
    return JSON.stringify({
      text: `A placeholder lore snippet about ${topic}, emitted by the mock client for pipeline testing.`,
      topics: ['mock', topic.toLowerCase().split(/\s+/)[0] || 'lore'],
    })
  }
  // Unknown template — return a minimal object so callers that expect
  // free-form text don't NPE, but template.parse will still throw loudly.
  return JSON.stringify({ mock: true, system: system.slice(0, 40), user: user.slice(0, 40) })
}

export interface MockLLMOptions {
  delayMs?: number
}

export class MockLLMClient implements LLMClient {
  readonly delayMs: number
  private calls = 0

  constructor(opts: MockLLMOptions = {}) {
    this.delayMs = opts.delayMs ?? 250
  }

  get callCount(): number {
    return this.calls
  }

  async complete(req: LLMCompletionRequest): Promise<LLMCompletionResponse> {
    this.calls += 1
    const system = lastContent(req, 'system')
    const user = lastContent(req, 'user')
    console.info('[MockLLMClient] call', this.calls, '| user:', user)
    if (this.delayMs > 0) await new Promise((r) => setTimeout(r, this.delayMs))
    return { content: mockResponse(system, user), model: 'mock-1', raw: { mock: true, user } }
  }
}
