import type { Drive } from '../game/drives'
import type { Rarity } from '../items/rarity'

export type RoomType =
  | 'safe'
  | 'corridor'
  | 'chamber'
  | 'crypt'
  | 'storage'
  /** Hearthside safe room — satisfies hunger and fatigue, no encounters. */
  | 'inn'
  /** Drinkable water or a fountain — satisfies hunger, low encounter chance. */
  | 'water'
  /** Two-way link to another area (teleporter, gate, elevator). */
  | 'portal'
  /** Marks where a dungeon / danger zone begins. */
  | 'entrance'
  /** Merchant or vending presence — future home of shopping. */
  | 'shop'
  /** Small consecrated / revered room; respawn anchor candidate. */
  | 'shrine'
  /** Edge-of-area exit that connects to a generated or existing area. */
  | 'exit'

// Canonical area kinds. Cross-world: a "settlement" means the same structural
// thing in fantasy (village), cyberpunk (district), and sci-fi (station hab).
// Per-world flavor lives in the world's context module.
export type AreaKind = 'settlement' | 'wilderness' | 'dungeon' | 'ruin'

export const AREA_KINDS: readonly AreaKind[] = [
  'settlement',
  'wilderness',
  'dungeon',
  'ruin',
] as const

export interface Position {
  areaId: string
  x: number
  y: number
  z: number
}

// Mechanics of a room: position, type, drives it can satisfy.
export interface RoomArchetype {
  x: number
  y: number
  z: number
  type: RoomType
  satisfies?: Drive[]
  /** Only on 'portal' rooms. Defines the area and entry position this portal leads to. */
  destination?: Position
  /** Only on 'exit' rooms. True when no generated area has been linked yet. */
  pendingAreaGeneration?: boolean
  /** When true, this exit always re-triggers LLM generation on entry —
   *  the previous destination (if any) is ignored. Each visit produces a
   *  fresh generated area, giving the player a reliable escape hatch to
   *  roll new content when the last generation was too hard or stale. */
  permanentFrontier?: boolean
  /** When true, this tile has been permanently flagged to skip LLM area
   *  generation — either because the player chose "Continue without
   *  generation" or because the generation timed out. Future visits
   *  bypass dialogs/fights and reveal the tile as empty content. */
  skipGeneration?: boolean
  /** When true, this exit is a Portal Hub — a single tile that offers a
   *  dialog for choosing between generating a fresh area or revisiting
   *  any area previously generated through this same portal. Stepping
   *  on it opens the portal-selection dialog instead of auto-triggering
   *  generation the way a plain permanentFrontier would. */
  portalHub?: boolean
  /** Areas generated through this Portal Hub, displayed as revisitable
   *  destinations in the portal-selection dialog. Grows unbounded —
   *  every generation through this hub appends an entry. */
  portalDestinations?: PortalDestination[]
}

export interface PortalDestination {
  /** Generated area id — used to traverse the portal. */
  areaId: string
  /** Display name shown in the portal dialog (the area's generated name). */
  name: string
  /** Epoch ms when the area was generated — used for sorting by recency. */
  generatedAt: number
}

// Flavor of a room: name, description, and per-drive action narration.
export interface RoomFlavor {
  name: string
  description: string
  /** Narrative shown when a listed drive is satisfied here. Keyed by drive. */
  satisfyText?: Partial<Record<Drive, string>>
  /** Curated encounter override for this room. When set, the room's
   *  spawn roll picks this specific mob id from the world pool at the
   *  configured rarity instead of a random pool draw. firstOnly flags a
   *  one-shot spawn — once defeated, the curated entry drops out and
   *  the room reverts to the random pool. */
  encounter?: RoomEncounter
  /** Fixed NPC standing in this room — generated by the area-gen LLM
   *  pass, baked into the cached area, and replayed verbatim every
   *  visit. Greets the character on room entry; dialogue varies by
   *  visit count and (for one chosen axis per NPC) the character's
   *  class or species. Frontier overrides activate when an exit room
   *  in the same area is unresolved or freshly resolved. */
  npc?: NPC
}

/** Axis the NPC keys their hook line off — generation-time coin flip.
 *  Each NPC picks exactly one. The `hooks` map is then keyed by the
 *  ids of that axis (class ids or species ids from the world). */
export type NPCCares = 'class' | 'species'

export interface NPC {
  /** Kebab-case slug, unique within the area. */
  id: string
  name: string
  /** Short role / archetype line ("retired guard", "vat-steward"). Not
   *  rendered directly — used by the LLM at gen time to keep dialogue
   *  in voice. Kept on the persisted shape so future tooling (popovers,
   *  dev inspector) has something to show. */
  role: string
  description: string
  /** Which character axis this NPC reacts to. Coin-flipped at
   *  generation time. */
  cares: NPCCares
  /** Per-axis-id hook line, e.g. `{ "wizard": "Spellslinger, eh?" }`
   *  when `cares === 'class'`. Prepended to `firstMeet` on first
   *  greeting. Missing entries fall through to a hookless first meet. */
  hooks: Record<string, string>
  /** First-time greeting. Played the first time the character enters
   *  the NPC's room. */
  firstMeet: string
  /** Subsequent greetings — rotated through by visit count once the
   *  character has met the NPC at least once. Must be non-empty for
   *  the NPC to feel alive on repeat visits; the parser tolerates an
   *  empty array by falling back to `firstMeet`. */
  regular: string[]
  /** Override line played when the NPC is near a frontier exit whose
   *  destination has not been generated yet. Optional — NPCs nowhere
   *  near a frontier omit it. */
  frontierUnknown?: string
  /** Override line played once the frontier has been generated. The
   *  string contains an `{areaName}` slot the engine substitutes at
   *  emit time. Optional. */
  frontierKnown?: string
}

export interface RoomEncounter {
  /** Mob id from the world's `mobs` pool. */
  mobId: string
  /** Rarity to spawn at. Overrides the level-based random rarity roll. */
  rarity: Rarity
  /** When true, defeating this curated encounter writes the room's
   *  visitedKey into `character.defeatedRooms` and the encounter will
   *  not respawn — the room falls back to the random pool. When false
   *  or absent the curated encounter is a permanent ambient fixture
   *  (still gated by the global encounter chance). */
  firstOnly?: boolean
  /** Optional curated loot override. When present, defeating this
   *  encounter drops exactly this table (not the mob's archetype loot).
   *  Only fires when the defeated mob was actually spawned from the
   *  curated entry (Mob.curated === true) so a random-pool spawn of
   *  the same mob id doesn't trigger the override. */
  loot?: RoomCuratedLoot
}

export interface RoomCuratedLoot {
  /** Gold payout range. Drops a random integer in [min, max]. Omit for
   *  a gold-less encounter. */
  gold?: { min: number; max: number }
  /** Curated item drops, each dropped deterministically on defeat
   *  (no per-drop chance roll — curated means guaranteed). Optional
   *  per-drop rarity/level overrides; absent ⇒ roll the usual way. */
  items?: RoomCuratedItem[]
}

export interface RoomCuratedItem {
  /** Item archetype id from the world's `items` library. */
  itemId: string
  /** Explicit rarity for the drop. Skips `rollDropRarity`. Absent ⇒
   *  roll as usual (biased by mob rarity + reward mult). */
  rarity?: Rarity
  /** Drop quantity. Absent ⇒ 1. */
  qty?: number
  /** Explicit item level. Skips `rollDropLevel`. Absent ⇒ roll around
   *  the mob's level with the usual jitter. */
  level?: number
}

export type Room = RoomArchetype & RoomFlavor

export interface Area {
  id: string
  name: string
  /** Optional rarity — drives the area-name color in the map header.
   *  Absent = treat as common for display purposes. */
  rarity?: Rarity
  /** Suggested character level for the area. Authored areas ship with
   *  hand-picked values; LLM-generated areas stamp the character's
   *  level at creation time. Absent = unknown tier (sorts last in UIs
   *  like the dev Area tab). */
  level?: number
  /** Canonical area kind — settlement / wilderness / dungeon / ruin.
   *  Authored areas assert this at definition time; generated areas
   *  stamp it from `pickAreaKind` at generation time and persist the
   *  value through the cache. Surfaced in the map panel header as a
   *  room-type-style chip. Optional for back-compat with pre-field
   *  cache entries. */
  kind?: AreaKind
  /** Epoch ms when this area was first generated (LLM pass). Absent on
   *  authored areas and on older cached areas that predate the stamp.
   *  Surfaced in the dev Area tab (as "3h ago") and in the Map's room
   *  index (paired with the creator fields below for a full provenance
   *  line). */
  generatedAt?: number
  /** Character name whose session triggered the LLM call that
   *  generated this area. Absent for authored areas and for cache
   *  entries that predate the stamp. */
  createdBy?: string
  /** Model id (e.g. "claude-opus-4-7") that produced the flavor pass.
   *  Absent for authored areas. */
  createdByModel?: string
  startX: number
  startY: number
  startZ: number
  rooms: Record<string, Room>
}

// Flavor of an area — the unit above Room. Not yet merged into Area itself
// (that's a later refactor); for now it exists so the LLM pipeline can
// generate an area's theme first and have roomFlavor stay consistent with it.
export interface AreaFlavor {
  name: string
  description: string
  /** Short keyword(s) downstream room generation keys on, e.g. "moldering crypt". */
  theme: string
}

export function roomKey(x: number, y: number, z: number): string {
  return `${x},${y},${z}`
}

export function visitedKey(areaId: string, x: number, y: number, z: number): string {
  return `${areaId}:${x},${y},${z}`
}
