import { getWorldManifest } from '../worlds'
import type { Character } from './types'

/**
 * Title ladder.
 *
 *   Index 0           Level 1 — birth title (shared across classes in a world).
 *   Index 1..24       Levels 2..25 — per-class, one title per level.
 *   Index 25..39      Levels 30, 35, 40, ..., 100 — per-class, every 5 levels.
 *   Index 40..        Levels 110, 120, ... — LLM-generated on demand.
 *
 * Indexes 1..39 are hand-authored in the world manifest. Index 40+ is
 * generated by the LLM and stored on `Character.generatedTitles` keyed by
 * the same index.
 */

/** The largest title index that is hand-authored in the manifest (level 100). */
export const LAST_AUTHORED_TITLE_INDEX = 39

/**
 * Returns the title index granted by reaching `level`, or null if this
 * particular level doesn't cross a title threshold.
 */
export function titleIndexForLevel(level: number): number | null {
  if (level < 1) return null
  if (level === 1) return 0
  if (level <= 25) return level - 1
  if (level <= 100) {
    if (level % 5 !== 0) return null
    return 24 + (level - 25) / 5
  }
  if (level % 10 !== 0) return null
  return 39 + (level - 100) / 10
}

/**
 * Returns the title index the character should be wearing at `level` — the
 * most recent threshold they've crossed. Unlike titleIndexForLevel this is
 * defined for every level ≥ 1.
 */
export function currentTitleIndex(level: number): number {
  if (level <= 1) return 0
  if (level <= 25) return level - 1
  if (level <= 100) {
    // Floor to the nearest multiple of 5. Levels 26-29 stay on the level-25
    // title (index 24) because the next authored threshold is at 30.
    const floored = Math.floor(level / 5) * 5
    if (floored < 30) return 24
    return 24 + (floored - 25) / 5
  }
  const floored = Math.floor(level / 10) * 10
  return 39 + (floored - 100) / 10
}

/** Inverse of titleIndexForLevel — the level at which `index` is earned. */
export function levelForTitleIndex(index: number): number {
  if (index <= 0) return 1
  if (index <= 24) return index + 1
  if (index <= 39) return 25 + (index - 24) * 5
  return 100 + (index - 39) * 10
}

export type TitleSource = 'authored' | 'generated' | 'missing'

export interface TitleResolution {
  index: number
  level: number
  text: string | null
  source: TitleSource
}

/**
 * Resolves the title for a given `index` against a character's world + class
 * manifest and their stash of LLM-generated titles. Missing = not authored
 * and not yet generated; caller decides whether to request generation.
 */
export function resolveTitle(character: Character, index: number): TitleResolution {
  const level = levelForTitleIndex(index)
  const manifest = getWorldManifest(character.worldId)
  if (!manifest) return { index, level, text: null, source: 'missing' }

  if (index === 0) {
    const text = manifest.birthTitle ?? null
    return { index, level, text, source: text ? 'authored' : 'missing' }
  }

  if (index <= LAST_AUTHORED_TITLE_INDEX) {
    const klass = manifest.classes.find((c) => c.id === character.classId)
    const text = klass?.titles?.[index - 1] ?? null
    return { index, level, text, source: text ? 'authored' : 'missing' }
  }

  const generated = character.generatedTitles?.[index]
  return {
    index,
    level,
    text: generated ?? null,
    source: generated ? 'generated' : 'missing',
  }
}

/** Convenience: the title the character is currently wearing. */
export function currentTitle(character: Character): TitleResolution {
  return resolveTitle(character, currentTitleIndex(character.level))
}
