import type { SpellDef } from './types'

// Per-world spell libraries. Each world picks a flavor (magic / hack /
// psionics) but the mechanical shapes are shared: damage, DoT, heal,
// buff, debuff, and a level-4 escape/teleport. Buff/debuff/DoT
// conditionIds reference the world's own conditions library.
//
// Scripted level progression (unlockLevel field):
//   - level 1:  Magic Missile / Icepick / Psi-Bolt       (basic damage)
//   - level 5:  Fireball / Overload / Mind Storm         (heavier damage)
//   - level 7:  Chain Lightning / Daemon Cascade / ...   (multi-hit)
//   - level 10: Ice Armor / Hardline / Shield-Field      (self buff)
//   - level 15: Greater/True Heal                        (self heal)
// Post-level-15 spells come from the LLM path (see progression.ts).
//
// Mana costs scale with power: lv1 ≈ 2-5, lv2 ≈ 6-10, lv3 ≈ 12-18, higher
// lines climb toward 25-30 for the capstone heal.

const FANTASY: SpellDef[] = [
  {
    id: 'magic_missile',
    name: 'Magic Missile',
    level: 1,
    magicCost: 3,
    description: 'A dart of raw arcana. Unerring, small, enough to start.',
    target: 'enemy',
    targetKind: 'mob',
    effect: { kind: 'damage', amount: 4 },
    scrollIntRequirement: 8,
    unlockLevel: 1,
    element: 'electric',
    verbs: {
      grazing: ['pings', 'taps'],
      light: ['darts at', 'jabs at'],
      solid: ['lances', 'strikes'],
      heavy: ['pierces', 'rips at'],
      severe: ['SKEWERS', 'SPEARS'],
      critical: ['SHATTERS', 'UNMAKES'],
    },
  },
  {
    id: 'fireball',
    name: 'Fireball',
    level: 2,
    magicCost: 8,
    description: 'A blooming flower of flame. Singes, sizzles, scorches.',
    target: 'enemy',
    targetKind: 'mob',
    effect: { kind: 'damage', amount: 8 },
    scrollIntRequirement: 11,
    unlockLevel: 5,
    element: 'fire',
    verbs: {
      grazing: ['singes', 'warms'],
      light: ['sizzles', 'scorches'],
      solid: ['burns', 'ignites'],
      heavy: ['SEARS', 'ROASTS'],
      severe: ['IMMOLATES', 'TORCHES'],
      critical: ['INCINERATES', 'CREMATES'],
    },
  },
  {
    id: 'chain_lightning',
    name: 'Chain Lightning',
    level: 3,
    magicCost: 14,
    description: 'A fork of light leaps three times before it dies. You smell ozone in your hair.',
    target: 'enemy',
    targetKind: 'mob',
    effect: { kind: 'multi-damage', amount: 5, hits: 3 },
    scrollIntRequirement: 14,
    unlockLevel: 7,
    element: 'electric',
    verbs: {
      grazing: ['arcs at', 'sparks past'],
      light: ['jolts', 'shocks'],
      solid: ['electrocutes', 'fries'],
      heavy: ['OVERLOADS', 'SCORCHES'],
      severe: ['ELECTROCUTES', 'FLASHES'],
      critical: ['DISINTEGRATES', 'BURNS OUT'],
    },
  },
  {
    id: 'ice_armor',
    name: 'Ice Armor',
    level: 3,
    magicCost: 12,
    description: 'A second skin of glacier-glass closes around you. Everything that bites, bites glass first.',
    target: 'self',
    targetKind: 'self',
    effect: { kind: 'buff', conditionId: 'ice_armored' },
    scrollIntRequirement: 14,
    unlockLevel: 10,
    element: 'ice',
  },
  {
    id: 'poison_bolt',
    name: 'Poison Bolt',
    level: 2,
    magicCost: 5,
    description: "Green on the tongue. The target doesn't feel it until later.",
    target: 'enemy',
    targetKind: 'mob',
    effect: { kind: 'damage-over-time', conditionId: 'poisoned' },
    scrollIntRequirement: 11,
    element: 'earth',
  },
  {
    id: 'lesser_heal',
    name: 'Lesser Heal',
    level: 1,
    magicCost: 4,
    description: 'A small warmth under the wound.',
    target: 'self',
    targetKind: 'self',
    effect: { kind: 'heal', amount: 6 },
    scrollIntRequirement: 8,
    unlockLevel: 1,
  },
  {
    id: 'greater_heal',
    name: 'Greater Heal',
    level: 3,
    magicCost: 10,
    description: 'Flesh knits. Ribs realign. You could almost whistle.',
    target: 'self',
    targetKind: 'self',
    effect: { kind: 'heal', amount: 14 },
    scrollIntRequirement: 14,
  },
  {
    id: 'true_heal',
    name: 'True Heal',
    level: 4,
    magicCost: 25,
    description: 'A long, still breath. Every wound closes and every bruise fades.',
    target: 'self',
    targetKind: 'self',
    effect: { kind: 'heal', amount: 40 },
    scrollIntRequirement: 16,
    unlockLevel: 15,
  },
  {
    id: 'shield_of_faith',
    name: 'Shield of Faith',
    level: 2,
    magicCost: 6,
    description: 'A faint golden rim. You are harder to hurt, briefly.',
    target: 'self',
    targetKind: 'self',
    effect: { kind: 'buff', conditionId: 'blessed' },
    scrollIntRequirement: 11,
  },
  {
    id: 'recall',
    name: 'Recall',
    level: 4,
    magicCost: 15,
    description: 'The world folds once. You are safe.',
    target: 'self',
    targetKind: 'self',
    effect: { kind: 'teleport-safe' },
    scrollIntRequirement: 16,
  },
]

const CYBERPUNK: SpellDef[] = [
  {
    id: 'icepick',
    name: 'Icepick',
    level: 1,
    magicCost: 3,
    description: 'A needle through their stack. Low bandwidth, reliable.',
    target: 'enemy',
    targetKind: 'mob',
    effect: { kind: 'damage', amount: 4 },
    scrollIntRequirement: 8,
    unlockLevel: 1,
    element: 'ice',
    verbs: {
      grazing: ['pings', 'nudges'],
      light: ['stabs', 'pokes'],
      solid: ['jacks', 'stings'],
      heavy: ['CRACKS', 'SPIKES'],
      severe: ['FRIES', 'BURNS'],
      critical: ['BRICKS', 'BLUESCREENS'],
    },
  },
  {
    id: 'overload',
    name: 'Overload',
    level: 2,
    magicCost: 8,
    description: 'Their cooling loop fights back. It loses.',
    target: 'enemy',
    targetKind: 'mob',
    effect: { kind: 'damage', amount: 8 },
    scrollIntRequirement: 11,
    unlockLevel: 5,
    element: 'electric',
    verbs: {
      grazing: ['warms', 'strains'],
      light: ['heats', 'taxes'],
      solid: ['loads', 'burns'],
      heavy: ['OVERLOADS', 'THERMALS'],
      severe: ['FRIES', 'MELTS'],
      critical: ['VAPORIZES', 'ASHES'],
    },
  },
  {
    id: 'daemon_cascade',
    name: 'Daemon Cascade',
    level: 3,
    magicCost: 14,
    description: 'A worm that forks twice, burns three sockets, and leaves no log.',
    target: 'enemy',
    targetKind: 'mob',
    effect: { kind: 'multi-damage', amount: 5, hits: 3 },
    scrollIntRequirement: 14,
    unlockLevel: 7,
    element: 'electric',
    verbs: {
      grazing: ['glitches', 'stutters'],
      light: ['corrupts', 'scrambles'],
      solid: ['hijacks', 'pwns'],
      heavy: ['SHREDS', 'WIPES'],
      severe: ['BRICKS', 'FORMATS'],
      critical: ['DELETES', 'NULLROUTES'],
    },
  },
  {
    id: 'hardline',
    name: 'Hardline',
    level: 3,
    magicCost: 12,
    description: 'Reactive armor wakes up. Incoming packets break at the seam.',
    target: 'self',
    targetKind: 'self',
    effect: { kind: 'buff', conditionId: 'ice_armored' },
    scrollIntRequirement: 14,
    unlockLevel: 10,
    element: 'ice',
  },
  {
    id: 'hack_attack',
    name: 'Hack Attack',
    level: 2,
    magicCost: 5,
    description: 'A script slips in. Their reflexes lag by one frame — just enough.',
    target: 'enemy',
    targetKind: 'mob',
    effect: { kind: 'debuff', conditionId: 'hacked' },
    scrollIntRequirement: 11,
    element: 'hack',
  },
  {
    id: 'patch_kit',
    name: 'Patch Kit',
    level: 1,
    magicCost: 4,
    description: 'A crude biomesh. Good enough for now.',
    target: 'self',
    targetKind: 'self',
    effect: { kind: 'heal', amount: 6 },
    scrollIntRequirement: 8,
    unlockLevel: 1,
  },
  {
    id: 'autoinjector',
    name: 'Autoinjector',
    level: 3,
    magicCost: 10,
    description: 'The shot you saved for the worst night.',
    target: 'self',
    targetKind: 'self',
    effect: { kind: 'heal', amount: 14 },
    scrollIntRequirement: 14,
  },
  {
    id: 'trauma_reboot',
    name: 'Trauma Reboot',
    level: 4,
    magicCost: 25,
    description: 'Every implant fires at once. You come back clean.',
    target: 'self',
    targetKind: 'self',
    effect: { kind: 'heal', amount: 40 },
    scrollIntRequirement: 16,
    unlockLevel: 15,
  },
  {
    id: 'overclock_self',
    name: 'Overclock',
    level: 2,
    magicCost: 6,
    description: 'Reflex loop strapped to the red line. Strikes land harder, briefly.',
    target: 'self',
    targetKind: 'self',
    effect: { kind: 'buff', conditionId: 'overclocked' },
    scrollIntRequirement: 11,
  },
  {
    id: 'extract',
    name: 'Extract',
    level: 4,
    magicCost: 15,
    description: 'The safehouse door blinks open where your hand was.',
    target: 'self',
    targetKind: 'self',
    effect: { kind: 'teleport-safe' },
    scrollIntRequirement: 16,
  },
]

const SCIFI: SpellDef[] = [
  {
    id: 'psi_bolt',
    name: 'Psi-Bolt',
    level: 1,
    magicCost: 3,
    description: 'A thought, sharpened.',
    target: 'enemy',
    targetKind: 'mob',
    effect: { kind: 'damage', amount: 4 },
    scrollIntRequirement: 8,
    unlockLevel: 1,
    element: 'electric',
    verbs: {
      grazing: ['brushes', 'grazes'],
      light: ['stings', 'pricks'],
      solid: ['jolts', 'shocks'],
      heavy: ['ROILS', 'LANCES'],
      severe: ['CRUSHES', 'RIPS'],
      critical: ['SHATTERS', 'UNMAKES'],
    },
  },
  {
    id: 'mind_storm',
    name: 'Mind Storm',
    level: 2,
    magicCost: 8,
    description: 'Their thoughts fold inward, howling.',
    target: 'enemy',
    targetKind: 'mob',
    effect: { kind: 'damage', amount: 8 },
    scrollIntRequirement: 11,
    unlockLevel: 5,
    element: 'hack',
    verbs: {
      grazing: ['buzzes', 'needles'],
      light: ['rings', 'rattles'],
      solid: ['bursts over', 'rolls through'],
      heavy: ['LASHES', 'THROTTLES'],
      severe: ['SUNDERS', 'BATTERS'],
      critical: ['ANNIHILATES', 'ERASES'],
    },
  },
  {
    id: 'quantum_cascade',
    name: 'Quantum Cascade',
    level: 3,
    magicCost: 14,
    description: 'The thought forks three ways, each one landing a heartbeat apart.',
    target: 'enemy',
    targetKind: 'mob',
    effect: { kind: 'multi-damage', amount: 5, hits: 3 },
    scrollIntRequirement: 14,
    unlockLevel: 7,
    element: 'electric',
    verbs: {
      grazing: ['arcs at', 'forks past'],
      light: ['jolts', 'crackles over'],
      solid: ['cascades over', 'lashes'],
      heavy: ['OVERLOADS', 'FLASHES'],
      severe: ['ELECTROCUTES', 'SCORCHES'],
      critical: ['DISINTEGRATES', 'VAPORIZES'],
    },
  },
  {
    id: 'radiant_burst',
    name: 'Radiant Burst',
    level: 2,
    magicCost: 5,
    description: 'A quiet wash of particles. They feel it tomorrow, not today.',
    target: 'enemy',
    targetKind: 'mob',
    effect: { kind: 'damage-over-time', conditionId: 'irradiated' },
    scrollIntRequirement: 11,
    element: 'fire',
  },
  {
    id: 'bioregen',
    name: 'Bioregen',
    level: 1,
    magicCost: 4,
    description: "Cells remember what they're supposed to be.",
    target: 'self',
    targetKind: 'self',
    effect: { kind: 'heal', amount: 6 },
    scrollIntRequirement: 8,
    unlockLevel: 1,
  },
  {
    id: 'field_mend',
    name: 'Field Mend',
    level: 3,
    magicCost: 10,
    description: 'A long exhale. Everything that hurt stops.',
    target: 'self',
    targetKind: 'self',
    effect: { kind: 'heal', amount: 14 },
    scrollIntRequirement: 14,
  },
  {
    id: 'cryo_carapace',
    name: 'Cryo-Carapace',
    level: 3,
    magicCost: 12,
    description: 'Cold crystals climb your skin and fix themselves to the seam. The ice drinks the first wound.',
    target: 'self',
    targetKind: 'self',
    effect: { kind: 'buff', conditionId: 'shielded' },
    scrollIntRequirement: 14,
    unlockLevel: 10,
    element: 'ice',
  },
  {
    id: 'force_field',
    name: 'Force Field',
    level: 2,
    magicCost: 6,
    description: 'A soft edge around you that edges die against.',
    target: 'self',
    targetKind: 'self',
    effect: { kind: 'buff', conditionId: 'shielded' },
    scrollIntRequirement: 11,
  },
  {
    id: 'total_regen',
    name: 'Total Regen',
    level: 4,
    magicCost: 25,
    description: 'Every torn thread finds its spool. You remember what intact felt like.',
    target: 'self',
    targetKind: 'self',
    effect: { kind: 'heal', amount: 40 },
    scrollIntRequirement: 16,
    unlockLevel: 15,
  },
  {
    id: 'beam_out',
    name: 'Beam Out',
    level: 4,
    magicCost: 15,
    description: 'A column of light. Gone.',
    target: 'self',
    targetKind: 'self',
    effect: { kind: 'teleport-safe' },
    scrollIntRequirement: 16,
  },
]

export const WORLD_SPELLS: Record<string, SpellDef[]> = {
  fantasy: FANTASY,
  cyberpunk: CYBERPUNK,
  scifi: SCIFI,
}

/**
 * In-process cache for generated spells from `generateSpellForLevel`. Keyed
 * by spellId. Today this is a module-scoped map — not persisted across
 * reloads. A future real LLM integration should store the generated
 * definitions on the Character itself so they survive saves, the same way
 * curated areas are cached onto the world.
 */
const GENERATED_SPELLS: Record<string, SpellDef> = {}

/** Registers a generated spell so subsequent `getSpell` lookups resolve it. */
export function registerGeneratedSpell(spell: SpellDef): void {
  GENERATED_SPELLS[spell.id] = spell
}

export function getSpell(worldId: string, spellId: string): SpellDef | undefined {
  const curated = (WORLD_SPELLS[worldId] ?? []).find((s) => s.id === spellId)
  return curated ?? GENERATED_SPELLS[spellId]
}

export function getSpellList(worldId: string): SpellDef[] {
  return WORLD_SPELLS[worldId] ?? []
}
