import type { SpellDef } from './types'

// Per-world spell libraries. Each world picks a flavor (magic / hack /
// psionics) but the mechanical shapes are shared: damage, DoT, heal,
// buff, debuff, and a level-4 escape/teleport. Buff/debuff/DoT
// conditionIds reference the world's own conditions library.

const FANTASY: SpellDef[] = [
  {
    id: 'magic_missile',
    name: 'Magic Missile',
    level: 1,
    magicCost: 2,
    description: 'A dart of raw arcana. Unerring, small, enough to start.',
    target: 'enemy',
    effect: { kind: 'damage', amount: 4 },
    scrollIntRequirement: 8,
    element: 'electric',
    verbs: {
      grazing: ['pings', 'taps'],
      light: ['darts at', 'jabs at'],
      solid: ['lances', 'strikes'],
      heavy: ['pierces', 'rips at'],
      severe: ['SKEWERS', 'SPEARS'],
      critical: ['SHATTERS', 'UNMAKES'],
    },
  },
  {
    id: 'fireball',
    name: 'Fireball',
    level: 2,
    magicCost: 4,
    description: 'A blooming flower of flame. Singes, sizzles, scorches.',
    target: 'enemy',
    effect: { kind: 'damage', amount: 8 },
    scrollIntRequirement: 11,
    element: 'fire',
    verbs: {
      grazing: ['singes', 'warms'],
      light: ['sizzles', 'scorches'],
      solid: ['burns', 'ignites'],
      heavy: ['SEARS', 'ROASTS'],
      severe: ['IMMOLATES', 'TORCHES'],
      critical: ['INCINERATES', 'CREMATES'],
    },
  },
  {
    id: 'poison_bolt',
    name: 'Poison Bolt',
    level: 2,
    magicCost: 3,
    description: "Green on the tongue. The target doesn't feel it until later.",
    target: 'enemy',
    effect: { kind: 'damage-over-time', conditionId: 'poisoned' },
    scrollIntRequirement: 11,
    element: 'earth',
  },
  {
    id: 'lesser_heal',
    name: 'Lesser Heal',
    level: 1,
    magicCost: 2,
    description: 'A small warmth under the wound.',
    target: 'self',
    effect: { kind: 'heal', amount: 6 },
    scrollIntRequirement: 8,
  },
  {
    id: 'greater_heal',
    name: 'Greater Heal',
    level: 3,
    magicCost: 5,
    description: 'Flesh knits. Ribs realign. You could almost whistle.',
    target: 'self',
    effect: { kind: 'heal', amount: 14 },
    scrollIntRequirement: 14,
  },
  {
    id: 'shield_of_faith',
    name: 'Shield of Faith',
    level: 2,
    magicCost: 3,
    description: 'A faint golden rim. You are harder to hurt, briefly.',
    target: 'self',
    effect: { kind: 'buff', conditionId: 'blessed' },
    scrollIntRequirement: 11,
  },
  {
    id: 'recall',
    name: 'Recall',
    level: 4,
    magicCost: 8,
    description: 'The world folds once. You are safe.',
    target: 'self',
    effect: { kind: 'teleport-safe' },
    scrollIntRequirement: 16,
  },
]

const CYBERPUNK: SpellDef[] = [
  {
    id: 'icepick',
    name: 'Icepick',
    level: 1,
    magicCost: 2,
    description: 'A needle through their stack. Low bandwidth, reliable.',
    target: 'enemy',
    effect: { kind: 'damage', amount: 4 },
    scrollIntRequirement: 8,
    element: 'ice',
    verbs: {
      grazing: ['pings', 'nudges'],
      light: ['stabs', 'pokes'],
      solid: ['jacks', 'stings'],
      heavy: ['CRACKS', 'SPIKES'],
      severe: ['FRIES', 'BURNS'],
      critical: ['BRICKS', 'BLUESCREENS'],
    },
  },
  {
    id: 'overload',
    name: 'Overload',
    level: 2,
    magicCost: 4,
    description: 'Their cooling loop fights back. It loses.',
    target: 'enemy',
    effect: { kind: 'damage', amount: 8 },
    scrollIntRequirement: 11,
    element: 'electric',
    verbs: {
      grazing: ['warms', 'strains'],
      light: ['heats', 'taxes'],
      solid: ['loads', 'burns'],
      heavy: ['OVERLOADS', 'THERMALS'],
      severe: ['FRIES', 'MELTS'],
      critical: ['VAPORIZES', 'ASHES'],
    },
  },
  {
    id: 'hack_attack',
    name: 'Hack Attack',
    level: 2,
    magicCost: 3,
    description: 'A script slips in. Their reflexes lag by one frame — just enough.',
    target: 'enemy',
    effect: { kind: 'debuff', conditionId: 'hacked' },
    scrollIntRequirement: 11,
    element: 'hack',
  },
  {
    id: 'patch_kit',
    name: 'Patch Kit',
    level: 1,
    magicCost: 2,
    description: 'A crude biomesh. Good enough for now.',
    target: 'self',
    effect: { kind: 'heal', amount: 6 },
    scrollIntRequirement: 8,
  },
  {
    id: 'autoinjector',
    name: 'Autoinjector',
    level: 3,
    magicCost: 5,
    description: 'The shot you saved for the worst night.',
    target: 'self',
    effect: { kind: 'heal', amount: 14 },
    scrollIntRequirement: 14,
  },
  {
    id: 'overclock_self',
    name: 'Overclock',
    level: 2,
    magicCost: 3,
    description: 'Reflex loop strapped to the red line. Strikes land harder, briefly.',
    target: 'self',
    effect: { kind: 'buff', conditionId: 'overclocked' },
    scrollIntRequirement: 11,
  },
  {
    id: 'extract',
    name: 'Extract',
    level: 4,
    magicCost: 8,
    description: 'The safehouse door blinks open where your hand was.',
    target: 'self',
    effect: { kind: 'teleport-safe' },
    scrollIntRequirement: 16,
  },
]

const SCIFI: SpellDef[] = [
  {
    id: 'psi_bolt',
    name: 'Psi-Bolt',
    level: 1,
    magicCost: 2,
    description: 'A thought, sharpened.',
    target: 'enemy',
    effect: { kind: 'damage', amount: 4 },
    scrollIntRequirement: 8,
    element: 'electric',
    verbs: {
      grazing: ['brushes', 'grazes'],
      light: ['stings', 'pricks'],
      solid: ['jolts', 'shocks'],
      heavy: ['ROILS', 'LANCES'],
      severe: ['CRUSHES', 'RIPS'],
      critical: ['SHATTERS', 'UNMAKES'],
    },
  },
  {
    id: 'mind_storm',
    name: 'Mind Storm',
    level: 2,
    magicCost: 4,
    description: 'Their thoughts fold inward, howling.',
    target: 'enemy',
    effect: { kind: 'damage', amount: 8 },
    scrollIntRequirement: 11,
    element: 'hack',
    verbs: {
      grazing: ['buzzes', 'needles'],
      light: ['rings', 'rattles'],
      solid: ['bursts over', 'rolls through'],
      heavy: ['LASHES', 'THROTTLES'],
      severe: ['SUNDERS', 'BATTERS'],
      critical: ['ANNIHILATES', 'ERASES'],
    },
  },
  {
    id: 'radiant_burst',
    name: 'Radiant Burst',
    level: 2,
    magicCost: 3,
    description: 'A quiet wash of particles. They feel it tomorrow, not today.',
    target: 'enemy',
    effect: { kind: 'damage-over-time', conditionId: 'irradiated' },
    scrollIntRequirement: 11,
    element: 'fire',
  },
  {
    id: 'bioregen',
    name: 'Bioregen',
    level: 1,
    magicCost: 2,
    description: "Cells remember what they're supposed to be.",
    target: 'self',
    effect: { kind: 'heal', amount: 6 },
    scrollIntRequirement: 8,
  },
  {
    id: 'field_mend',
    name: 'Field Mend',
    level: 3,
    magicCost: 5,
    description: 'A long exhale. Everything that hurt stops.',
    target: 'self',
    effect: { kind: 'heal', amount: 14 },
    scrollIntRequirement: 14,
  },
  {
    id: 'force_field',
    name: 'Force Field',
    level: 2,
    magicCost: 3,
    description: 'A soft edge around you that edges die against.',
    target: 'self',
    effect: { kind: 'buff', conditionId: 'shielded' },
    scrollIntRequirement: 11,
  },
  {
    id: 'beam_out',
    name: 'Beam Out',
    level: 4,
    magicCost: 8,
    description: 'A column of light. Gone.',
    target: 'self',
    effect: { kind: 'teleport-safe' },
    scrollIntRequirement: 16,
  },
]

export const WORLD_SPELLS: Record<string, SpellDef[]> = {
  fantasy: FANTASY,
  cyberpunk: CYBERPUNK,
  scifi: SCIFI,
}

export function getSpell(worldId: string, spellId: string): SpellDef | undefined {
  return (WORLD_SPELLS[worldId] ?? []).find((s) => s.id === spellId)
}

export function getSpellList(worldId: string): SpellDef[] {
  return WORLD_SPELLS[worldId] ?? []
}
