import type { VerbSet } from '../combat'
import type { ElementKind } from '../effects/types'

export type SpellLevel = 1 | 2 | 3 | 4 | 5

export type SpellTarget = 'self' | 'enemy'

/**
 * Who the spell aims at mechanically. A clean split that the cast pipeline
 * branches on:
 *   - `mob`  → damage / DoT / debuff — requires an active encounter
 *   - `self` → heal / buff / teleport-safe — applied to the caster
 *   - `item` → enchant / repair / identify style effects on an inventory item
 *             (not yet wired into gameplay; see cast.ts for the stub branch)
 *
 * Older authoring uses only `SpellTarget` ('self' | 'enemy'); `targetKind`
 * is a superset so the new `item` spells don't get mis-routed through the
 * enemy path. Absent ⇒ infer from `target` (self → self, enemy → mob).
 */
export type SpellTargetKind = 'mob' | 'self' | 'item'

export type SpellEffect =
  /** Direct damage to the target mob. */
  | { kind: 'damage'; amount: number }
  /** Applies a DoT condition (from world conditions) to the target. */
  | { kind: 'damage-over-time'; conditionId: string }
  /** Restores HP to the caster. */
  | { kind: 'heal'; amount: number }
  /** Applies a condition to the caster (buff) or target (debuff). */
  | { kind: 'buff'; conditionId: string }
  | { kind: 'debuff'; conditionId: string }
  /** Teleports caster to their last safe position and fully restores HP. */
  | { kind: 'teleport-safe' }
  /** Multi-hit spell — lands `hits` strikes of `amount` damage, each picking
   *  a fresh severity/verb so chain-lightning style reads as multiple
   *  separate impacts in the log. */
  | { kind: 'multi-damage'; amount: number; hits: number }
  /** Single-target item effect. Opaque stub for now — the cast pipeline
   *  resolves `kind: 'item-enchant'` as a narrative beat plus a tiny
   *  stat nudge on the targeted inventory item. */
  | { kind: 'item-enchant'; bonus: 'attack' | 'defense'; amount: number }

/** Per-severity verbs override the world's default combat verbs when a damage
 *  spell lands. Partial — missing tiers fall back to the world verb set. */
export type SpellVerbs = Partial<VerbSet>

export interface SpellDef {
  id: string
  name: string
  level: SpellLevel
  magicCost: number
  description: string
  target: SpellTarget
  /** Explicit target kind — see SpellTargetKind. Absent ⇒ derived from
   *  `target`. Authoring note: set this when the spell affects an
   *  inventory item (`item`) so the cast pipeline routes correctly. */
  targetKind?: SpellTargetKind
  effect: SpellEffect
  /** INT requirement to read this spell from a scroll. Gating:
   *   lv1 → 8  (most characters)
   *   lv2 → 11 (some)
   *   lv3 → 14 (trained)
   *   lv4 → 16 (highly trained)
   *   lv5 → 18 (masters) */
  scrollIntRequirement: number
  /** Optional spell-flavored verbs for damage-kind spells. Ignored otherwise. */
  verbs?: SpellVerbs
  /** Elemental overlay to trigger on the affected actor when this spell resolves. */
  element?: ElementKind
  /** Character level at which magic-using classes unlock this spell as part
   *  of their scripted progression. See spells/progression.ts. Absent on
   *  spells that are class-starter only or unlocked by other means. */
  unlockLevel?: number
  /** True for spells generated by the LLM path past the scripted progression.
   *  Cached entries set this so the post-cap cache-rehydrate can distinguish
   *  them from curated spells. */
  generated?: boolean
}
